(feat): add temporal coverage and data_provenance indexers on indicators refs 258077
eea/eea.dexterity.indicators pull request #37
Opened 2023-10-20 08:06 UTC by dobri1408

https://taskman.eionet.europa.eu/issues/258077

2023-10-26 11:31 UTC, avoinea requested changes

2023-10-26 11:31 UTC, avoinea commented on eea/dexterity/indicators/upgrades/configure.zcml
> +  </genericsetup:upgradeSteps>
@dobri1408 There is no need for an upgrade step in this case. Only changes in xml files from profiles need an upgrade step.

2023-10-26 11:31 UTC, avoinea commented on eea/dexterity/indicators/profiles/default/metadata.xml
> +  <version>6.1</version>
@dobri1408 No need to increase metadata version number as nothing changed in profiles / *.xml files.

2023-10-26 12:03 UTC, dobri1408 commented
I have removed the upgrade step.

2023-10-30 16:13 UTC, avoinea approved these changes

2023-10-30 16:25 UTC, merged